/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScoutRouteImport } from './routes/scout'
import { Route as NewsRouteImport } from './routes/news'
import { Route as LadderRouteImport } from './routes/ladder'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MatchMatchIdRouteImport } from './routes/match.$matchId'
import { Route as ApiPublicManifestRouteImport } from './routes/api/public/manifest'
import { Route as ApiPublicAppIconRouteImport } from './routes/api/public/app-icon'
import { Route as ApiPublicHooksPrecomputeInsightsRouteImport } from './routes/api/public/hooks/precompute-insights'

const ScoutRoute = ScoutRouteImport.update({
  id: '/scout',
  path: '/scout',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const LadderRoute = LadderRouteImport.update({
  id: '/ladder',
  path: '/ladder',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchMatchIdRoute = MatchMatchIdRouteImport.update({
  id: '/match/$matchId',
  path: '/match/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicManifestRoute = ApiPublicManifestRouteImport.update({
  id: '/api/public/manifest',
  path: '/api/public/manifest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAppIconRoute = ApiPublicAppIconRouteImport.update({
  id: '/api/public/app-icon',
  path: '/api/public/app-icon',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksPrecomputeInsightsRoute =
  ApiPublicHooksPrecomputeInsightsRouteImport.update({
    id: '/api/public/hooks/precompute-insights',
    path: '/api/public/hooks/precompute-insights',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ladder': typeof LadderRoute
  '/news': typeof NewsRoute
  '/scout': typeof ScoutRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/api/public/app-icon': typeof ApiPublicAppIconRoute
  '/api/public/manifest': typeof ApiPublicManifestRoute
  '/api/public/hooks/precompute-insights': typeof ApiPublicHooksPrecomputeInsightsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ladder': typeof LadderRoute
  '/news': typeof NewsRoute
  '/scout': typeof ScoutRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/api/public/app-icon': typeof ApiPublicAppIconRoute
  '/api/public/manifest': typeof ApiPublicManifestRoute
  '/api/public/hooks/precompute-insights': typeof ApiPublicHooksPrecomputeInsightsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ladder': typeof LadderRoute
  '/news': typeof NewsRoute
  '/scout': typeof ScoutRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/api/public/app-icon': typeof ApiPublicAppIconRoute
  '/api/public/manifest': typeof ApiPublicManifestRoute
  '/api/public/hooks/precompute-insights': typeof ApiPublicHooksPrecomputeInsightsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ladder'
    | '/news'
    | '/scout'
    | '/match/$matchId'
    | '/api/public/app-icon'
    | '/api/public/manifest'
    | '/api/public/hooks/precompute-insights'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ladder'
    | '/news'
    | '/scout'
    | '/match/$matchId'
    | '/api/public/app-icon'
    | '/api/public/manifest'
    | '/api/public/hooks/precompute-insights'
  id:
    | '__root__'
    | '/'
    | '/ladder'
    | '/news'
    | '/scout'
    | '/match/$matchId'
    | '/api/public/app-icon'
    | '/api/public/manifest'
    | '/api/public/hooks/precompute-insights'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LadderRoute: typeof LadderRoute
  NewsRoute: typeof NewsRoute
  ScoutRoute: typeof ScoutRoute
  MatchMatchIdRoute: typeof MatchMatchIdRoute
  ApiPublicAppIconRoute: typeof ApiPublicAppIconRoute
  ApiPublicManifestRoute: typeof ApiPublicManifestRoute
  ApiPublicHooksPrecomputeInsightsRoute: typeof ApiPublicHooksPrecomputeInsightsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scout': {
      id: '/scout'
      path: '/scout'
      fullPath: '/scout'
      preLoaderRoute: typeof ScoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ladder': {
      id: '/ladder'
      path: '/ladder'
      fullPath: '/ladder'
      preLoaderRoute: typeof LadderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$matchId': {
      id: '/match/$matchId'
      path: '/match/$matchId'
      fullPath: '/match/$matchId'
      preLoaderRoute: typeof MatchMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/manifest': {
      id: '/api/public/manifest'
      path: '/api/public/manifest'
      fullPath: '/api/public/manifest'
      preLoaderRoute: typeof ApiPublicManifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/app-icon': {
      id: '/api/public/app-icon'
      path: '/api/public/app-icon'
      fullPath: '/api/public/app-icon'
      preLoaderRoute: typeof ApiPublicAppIconRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/precompute-insights': {
      id: '/api/public/hooks/precompute-insights'
      path: '/api/public/hooks/precompute-insights'
      fullPath: '/api/public/hooks/precompute-insights'
      preLoaderRoute: typeof ApiPublicHooksPrecomputeInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LadderRoute: LadderRoute,
  NewsRoute: NewsRoute,
  ScoutRoute: ScoutRoute,
  MatchMatchIdRoute: MatchMatchIdRoute,
  ApiPublicAppIconRoute: ApiPublicAppIconRoute,
  ApiPublicManifestRoute: ApiPublicManifestRoute,
  ApiPublicHooksPrecomputeInsightsRoute: ApiPublicHooksPrecomputeInsightsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
