/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScoutRouteImport } from './routes/scout'
import { Route as NewsRouteImport } from './routes/news'
import { Route as LadderRouteImport } from './routes/ladder'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MatchMatchIdRouteImport } from './routes/match.$matchId'
import { Route as ApiScoutVoiceRouteImport } from './routes/api/scout-voice'
import { Route as PlayerTeamThemeKeyPlayerSlugRouteImport } from './routes/player.$teamThemeKey.$playerSlug'
import { Route as ApiPublicManifestRouteImport } from './routes/api/public/manifest'
import { Route as ApiPublicAppIconRouteImport } from './routes/api/public/app-icon'
import { Route as ApiPublicHooksRefreshOddsRouteImport } from './routes/api/public/hooks/refresh-odds'
import { Route as ApiPublicHooksRefreshNrlDataRouteImport } from './routes/api/public/hooks/refresh-nrl-data'
import { Route as ApiPublicHooksPrecomputeInsightsRouteImport } from './routes/api/public/hooks/precompute-insights'
import { Route as ApiPublicHooksModelHealthRouteImport } from './routes/api/public/hooks/model-health'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutRoute = ScoutRouteImport.update({
  id: '/scout',
  path: '/scout',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const LadderRoute = LadderRouteImport.update({
  id: '/ladder',
  path: '/ladder',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchMatchIdRoute = MatchMatchIdRouteImport.update({
  id: '/match/$matchId',
  path: '/match/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScoutVoiceRoute = ApiScoutVoiceRouteImport.update({
  id: '/api/scout-voice',
  path: '/api/scout-voice',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerTeamThemeKeyPlayerSlugRoute =
  PlayerTeamThemeKeyPlayerSlugRouteImport.update({
    id: '/player/$teamThemeKey/$playerSlug',
    path: '/player/$teamThemeKey/$playerSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicManifestRoute = ApiPublicManifestRouteImport.update({
  id: '/api/public/manifest',
  path: '/api/public/manifest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAppIconRoute = ApiPublicAppIconRouteImport.update({
  id: '/api/public/app-icon',
  path: '/api/public/app-icon',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRefreshOddsRoute =
  ApiPublicHooksRefreshOddsRouteImport.update({
    id: '/api/public/hooks/refresh-odds',
    path: '/api/public/hooks/refresh-odds',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRefreshNrlDataRoute =
  ApiPublicHooksRefreshNrlDataRouteImport.update({
    id: '/api/public/hooks/refresh-nrl-data',
    path: '/api/public/hooks/refresh-nrl-data',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPrecomputeInsightsRoute =
  ApiPublicHooksPrecomputeInsightsRouteImport.update({
    id: '/api/public/hooks/precompute-insights',
    path: '/api/public/hooks/precompute-insights',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksModelHealthRoute =
  ApiPublicHooksModelHealthRouteImport.update({
    id: '/api/public/hooks/model-health',
    path: '/api/public/hooks/model-health',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ladder': typeof LadderRoute
  '/news': typeof NewsRoute
  '/scout': typeof ScoutRoute
  '/settings': typeof SettingsRoute
  '/api/scout-voice': typeof ApiScoutVoiceRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/api/public/app-icon': typeof ApiPublicAppIconRoute
  '/api/public/manifest': typeof ApiPublicManifestRoute
  '/player/$teamThemeKey/$playerSlug': typeof PlayerTeamThemeKeyPlayerSlugRoute
  '/api/public/hooks/model-health': typeof ApiPublicHooksModelHealthRoute
  '/api/public/hooks/precompute-insights': typeof ApiPublicHooksPrecomputeInsightsRoute
  '/api/public/hooks/refresh-nrl-data': typeof ApiPublicHooksRefreshNrlDataRoute
  '/api/public/hooks/refresh-odds': typeof ApiPublicHooksRefreshOddsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ladder': typeof LadderRoute
  '/news': typeof NewsRoute
  '/scout': typeof ScoutRoute
  '/settings': typeof SettingsRoute
  '/api/scout-voice': typeof ApiScoutVoiceRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/api/public/app-icon': typeof ApiPublicAppIconRoute
  '/api/public/manifest': typeof ApiPublicManifestRoute
  '/player/$teamThemeKey/$playerSlug': typeof PlayerTeamThemeKeyPlayerSlugRoute
  '/api/public/hooks/model-health': typeof ApiPublicHooksModelHealthRoute
  '/api/public/hooks/precompute-insights': typeof ApiPublicHooksPrecomputeInsightsRoute
  '/api/public/hooks/refresh-nrl-data': typeof ApiPublicHooksRefreshNrlDataRoute
  '/api/public/hooks/refresh-odds': typeof ApiPublicHooksRefreshOddsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ladder': typeof LadderRoute
  '/news': typeof NewsRoute
  '/scout': typeof ScoutRoute
  '/settings': typeof SettingsRoute
  '/api/scout-voice': typeof ApiScoutVoiceRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/api/public/app-icon': typeof ApiPublicAppIconRoute
  '/api/public/manifest': typeof ApiPublicManifestRoute
  '/player/$teamThemeKey/$playerSlug': typeof PlayerTeamThemeKeyPlayerSlugRoute
  '/api/public/hooks/model-health': typeof ApiPublicHooksModelHealthRoute
  '/api/public/hooks/precompute-insights': typeof ApiPublicHooksPrecomputeInsightsRoute
  '/api/public/hooks/refresh-nrl-data': typeof ApiPublicHooksRefreshNrlDataRoute
  '/api/public/hooks/refresh-odds': typeof ApiPublicHooksRefreshOddsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ladder'
    | '/news'
    | '/scout'
    | '/settings'
    | '/api/scout-voice'
    | '/match/$matchId'
    | '/api/public/app-icon'
    | '/api/public/manifest'
    | '/player/$teamThemeKey/$playerSlug'
    | '/api/public/hooks/model-health'
    | '/api/public/hooks/precompute-insights'
    | '/api/public/hooks/refresh-nrl-data'
    | '/api/public/hooks/refresh-odds'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ladder'
    | '/news'
    | '/scout'
    | '/settings'
    | '/api/scout-voice'
    | '/match/$matchId'
    | '/api/public/app-icon'
    | '/api/public/manifest'
    | '/player/$teamThemeKey/$playerSlug'
    | '/api/public/hooks/model-health'
    | '/api/public/hooks/precompute-insights'
    | '/api/public/hooks/refresh-nrl-data'
    | '/api/public/hooks/refresh-odds'
  id:
    | '__root__'
    | '/'
    | '/ladder'
    | '/news'
    | '/scout'
    | '/settings'
    | '/api/scout-voice'
    | '/match/$matchId'
    | '/api/public/app-icon'
    | '/api/public/manifest'
    | '/player/$teamThemeKey/$playerSlug'
    | '/api/public/hooks/model-health'
    | '/api/public/hooks/precompute-insights'
    | '/api/public/hooks/refresh-nrl-data'
    | '/api/public/hooks/refresh-odds'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LadderRoute: typeof LadderRoute
  NewsRoute: typeof NewsRoute
  ScoutRoute: typeof ScoutRoute
  SettingsRoute: typeof SettingsRoute
  ApiScoutVoiceRoute: typeof ApiScoutVoiceRoute
  MatchMatchIdRoute: typeof MatchMatchIdRoute
  ApiPublicAppIconRoute: typeof ApiPublicAppIconRoute
  ApiPublicManifestRoute: typeof ApiPublicManifestRoute
  PlayerTeamThemeKeyPlayerSlugRoute: typeof PlayerTeamThemeKeyPlayerSlugRoute
  ApiPublicHooksModelHealthRoute: typeof ApiPublicHooksModelHealthRoute
  ApiPublicHooksPrecomputeInsightsRoute: typeof ApiPublicHooksPrecomputeInsightsRoute
  ApiPublicHooksRefreshNrlDataRoute: typeof ApiPublicHooksRefreshNrlDataRoute
  ApiPublicHooksRefreshOddsRoute: typeof ApiPublicHooksRefreshOddsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scout': {
      id: '/scout'
      path: '/scout'
      fullPath: '/scout'
      preLoaderRoute: typeof ScoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ladder': {
      id: '/ladder'
      path: '/ladder'
      fullPath: '/ladder'
      preLoaderRoute: typeof LadderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$matchId': {
      id: '/match/$matchId'
      path: '/match/$matchId'
      fullPath: '/match/$matchId'
      preLoaderRoute: typeof MatchMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scout-voice': {
      id: '/api/scout-voice'
      path: '/api/scout-voice'
      fullPath: '/api/scout-voice'
      preLoaderRoute: typeof ApiScoutVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/$teamThemeKey/$playerSlug': {
      id: '/player/$teamThemeKey/$playerSlug'
      path: '/player/$teamThemeKey/$playerSlug'
      fullPath: '/player/$teamThemeKey/$playerSlug'
      preLoaderRoute: typeof PlayerTeamThemeKeyPlayerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/manifest': {
      id: '/api/public/manifest'
      path: '/api/public/manifest'
      fullPath: '/api/public/manifest'
      preLoaderRoute: typeof ApiPublicManifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/app-icon': {
      id: '/api/public/app-icon'
      path: '/api/public/app-icon'
      fullPath: '/api/public/app-icon'
      preLoaderRoute: typeof ApiPublicAppIconRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/refresh-odds': {
      id: '/api/public/hooks/refresh-odds'
      path: '/api/public/hooks/refresh-odds'
      fullPath: '/api/public/hooks/refresh-odds'
      preLoaderRoute: typeof ApiPublicHooksRefreshOddsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/refresh-nrl-data': {
      id: '/api/public/hooks/refresh-nrl-data'
      path: '/api/public/hooks/refresh-nrl-data'
      fullPath: '/api/public/hooks/refresh-nrl-data'
      preLoaderRoute: typeof ApiPublicHooksRefreshNrlDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/precompute-insights': {
      id: '/api/public/hooks/precompute-insights'
      path: '/api/public/hooks/precompute-insights'
      fullPath: '/api/public/hooks/precompute-insights'
      preLoaderRoute: typeof ApiPublicHooksPrecomputeInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/model-health': {
      id: '/api/public/hooks/model-health'
      path: '/api/public/hooks/model-health'
      fullPath: '/api/public/hooks/model-health'
      preLoaderRoute: typeof ApiPublicHooksModelHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LadderRoute: LadderRoute,
  NewsRoute: NewsRoute,
  ScoutRoute: ScoutRoute,
  SettingsRoute: SettingsRoute,
  ApiScoutVoiceRoute: ApiScoutVoiceRoute,
  MatchMatchIdRoute: MatchMatchIdRoute,
  ApiPublicAppIconRoute: ApiPublicAppIconRoute,
  ApiPublicManifestRoute: ApiPublicManifestRoute,
  PlayerTeamThemeKeyPlayerSlugRoute: PlayerTeamThemeKeyPlayerSlugRoute,
  ApiPublicHooksModelHealthRoute: ApiPublicHooksModelHealthRoute,
  ApiPublicHooksPrecomputeInsightsRoute: ApiPublicHooksPrecomputeInsightsRoute,
  ApiPublicHooksRefreshNrlDataRoute: ApiPublicHooksRefreshNrlDataRoute,
  ApiPublicHooksRefreshOddsRoute: ApiPublicHooksRefreshOddsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
